### ISSUE TITLE
Failed to build in android RN 0.47.2

### ISSUE THREAD

**Issue by MamiNomura** [Michaelvilleneuve/react-native-photo-gallery#8]
android/src/main/java/com/reactnative/photoview/PhotoViewPackage.java:18: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: node_modules/react-native-photo-view/android/src/main/java/com/reactnative/photoview/ResourceDrawableIdHelper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:react-native-photo-view:compileReleaseJavaWithJavac FAILED

react-native-cli: 2.0.1
react-native: 0.47.2

https://github.com/alwx/react-native-photo-view/issues/80
